### ISSUE TITLE
svg-inline-loader

### ISSUE THREAD

**Issue by peter-mouland** [electrode-io/isomorphic-loader#3]
hey, thought i'd try this plugin out as it looked like a good, simple solution.

unfortunately, I tried to do something that i do not think is supported.  It would be awsome if this would allow me to load the svg's inline, withint the html rather than just for another http request in the browser.

Do you know if this is possible or would be something you'd be interested in supporting?

I have tried it out in a branch of my example universal react app here: https://github.com/peter-mouland/react-lego/tree/svg-isomorphic-loader

**Comment by jchip** [comment]
I think this would be possible and easier for client side since something like file-loader can just emit the content of the file into the bundle.

On the server side it's trickier because the server ultimately only execute the UI code with `renderToString` and spits out HTML, but has no control over the bundle JS file.  On the server, one way is the iso loader could return a reference (maybe a URL) to the SVG object in the document instead of a HTTP URL, but then that requires you to some how get that SVG object into your document somewhere else.

If I find time, I will play with it to see what's possible.

**Comment by lefam** [comment]
Any news on this issue?

**Comment by peter-mouland** [comment]
my solution, which seems to work for me (although using some _undocumented_ features) is to do this on the server:
```js

const hook = require('node-hook');
const SvgLoader = require('svg-inline-loader')

    hook.hook('.svg', (source) => {
      const markup = SvgLoader.getExtractedSVG(source, { removeSVGTagAttrs: false });
      return 'module.exports = ' + JSON.stringify(markup);
    });
```

**Comment by lefam** [comment]
@peter-mouland I like your solution. Thanks.

**Comment by jchip** [comment]
@peter-mouland would that inject the SVG markup into the HTML multiple times if you reference it in multiple locations?

**Comment by peter-mouland** [comment]
yeah, it will.  

I suspect if you want to re-use then you could either us an svg-sprite generator or go for the inline reference method....

http://codepen.io/peter-mouland/full/JErvZY/
